export const FETCH_GAMES = Symbol('FETCH_GAMES');
export const FETCH_GAMES_SUCCESS = Symbol('FETCH_GAMES_SUCCESS');
export const FETCH_GAMES_FAILURE = Symbol('FETCH_GAMES_FAILURE');

export const FETCH_SLIDES = Symbol('FETCH_SLIDES');
export const FETCH_SLIDES_SUCCESS = Symbol('FETCH_SLIDES_SUCCESS');
export const FETCH_SLIDES_FAILURE = Symbol('FETCH_SLIDES_FAILURE');
